name: Case Sensitivity check

on:
  push:
    paths:
      - 'submissions/**.gds'
      - 'submissions/**.GDS'
      - 'submissions/**.oas'
      - 'submissions/**.OAS'
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  case-sensitivity_job:
    runs-on: ubuntu-latest
    name: check-file-case-sensitivity
    steps:
      # Checkout the source code so we have some files to look at.
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Run the case checker action
      - name: Check Case Sensitivity
        uses: credfeto/action-case-checker@v1.3.0

